[package]
name = "ambientweather"
version = "0.1.0"
authors = ["Jake McKnight <jake.mcknight@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
