[package]
name = "ambientweather"
version = "0.1.0"
authors = ["Jake McKnight <jake.mcknight@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
